export const ANKLET_LINK_STYLE_OPTIONS = [
  'Braided-Style',
  'Diamond-Cut',
  'Domed',
  'Fancy',
  'Oval',
  'Twisted',
  'Flat',
  'Puffed',
  'Graduated',
  'Round',
  'Double',
  'Hollow',
  'Square',
];

export const ANKLET_LINK_TYPE_OPTIONS = [
  'Mesh Link',
  'Byzantine Link',
  'Anchor Link',
  'Cable Link',
  'Ball Link',
  'Cobra Link',
  'Panther Link',
  'Bar Link',
  'Curb Link',
  'Popcorn Link',
  'King Link',
  'Omega Link',
  'Singapore Link',
  'Snail Link',
  'Snake Link',
  'Venezia Link',
  'Battuta Link',
  'Figaro Link',
  'Rolo Link',
  'Wheat Link',
  'Bead Link',
  'Foxtail Link',
  'Rope Link',
  'Bevel-Herringbone Link',
  'Gucci Link',
  'Scroll Link',
  'Box Link',
  'Herringbone Link',
  'Serpentine Link',
];
