export const BAND_DESIGN_STYLE_OPTIONS = [
  'Contoured',
  'Two-Row',
  'Four-Across',
  'Nine-Across',
  'Spaced',
  'Three-Row',
  'Five-Across',
  'Ten-Across',
  'Braided',
  'Twisted',
  'Across',
  'Six-Across',
  'Comfort-Fit',
  'Two-Across',
  'Seven-Across',
  'Scattered',
  'Interlocking',
  'Three-Across',
  'Eight-Across',
  'Soft-Square',
];

export const BAND_TYPE_OPTIONS = [
  'Anniversary',
  'Masonic',
  'Nugget-Style',
  'Solitaire',
  'Birthstone',
  'Matching',
  'Pinky',
  'Cluster',
  'Matching Wedding',
  'Rolling',
  'Three-Quarter Eternity',
  'Trinity',
  'Eternity',
  'Nugget',
  'Semi-Eternity',
  'Wedding',
];

export const BAND_SHANK_OPTIONS = [
  'With A Bypass Shank',
  'With A Comfort-Fit Shank',
  'With A Euro-Shank',
  'With A Flat Shank',
  'With A Half-Round Shank',
  'With A Hinged/clip-On Shank',
  'With A Knife-Edge Shank',
  'With A Soft-Square Shank',
  'With A Stirrup Shank',
  'With A Tapered Shank',
  'With A Tapered, Comfort-Fit Shank',
  'With An Adjustable Shank',
];
