export const CHAIN_LINK_STYLE_OPTIONS = [
  'Braided-Style',
  'Diamond-Cut',
  'Domed',
  'Fancy',
  'Oval',
  'Size-Adjustable',
  'Flat',
  'Puffed',
  'Square',
  'Graduated',
  'Rectangular',
  'Station',
  'Round',
  'Twisted',
  'Double',
  'Hollow',
];

export const CHAIN_LINK_TYPE_OPTIONS = [
  'Anchor Link',
  'Ball Link',
  'C-Link',
  'Cable Link',
  'Cobra Link',
  'Herringbone Link',
  'King Link',
  'Mesh Link',
  'Serpentine Link',
  'Singapore Link',
  'Snail Link',
  'Bar Link',
  'Battuta Link',
  'Cuban Link',
  'Omega Link',
  'Snake Link',
  'Bead Link',
  'Curb Link',
  'Panther Link',
  'Sparkle Link',
  'Belcher Link',
  'Double Link',
  'Popcorn Link',
  'Spiga Link',
  'Bevel-Herringbone Link',
  'Figaro Link',
  'Rolo Link',
  'Station Bead Link',
  'Bismark Link',
  'Foxtail Link',
  'Rope Link',
  'Box Link',
  'Franco Link',
  'Byzantine Link',
  'Gucci Link',
  'Scroll Link',
  'Saduza Link',
  'Trace Link',
  'Venezia Link',
  'Wheat Link',
];
