export const EARRING_TYPE_OPTIONS = [
  'Anticlastic',
  'Cuff',
  'Hoop',
  'Nugget-Style',
  'Ballerina',
  'Dangle',
  'Huggy-Style',
  'Screw-On',
  'Chandelier-Style',
  'Drop',
  'Lever-Back',
  'Shepherd Hook',
  'Clip-On',
  'Halo',
  'Magnetic',
  'Stud',
  'Cluster',
  'Hinged/clip-On',
  'Matching',
  'Trinity',
  'Coin',
  'Hook',
  'Nugget',
];

export const BACKINGS_TYPE_OPTIONS = [
  "With 'Earring Lock' Post/Back System",
  'With Friction Backs',
  'With Protektor Backs',
  'With Silicone Grip Backs',
  'With Bead Backs',
  'With Butterfly Backs',
  'With French Backs',
  'With Lever Backs',
  'With Locking Backs',
  'With Omega-Wire Backs',
  'With Push Backs',
  'With Push-On/Screw-Off Backs',
  'With Screw Backs',
];
