export const PENDANT_STYLE_OPTIONS = [
  'Modern-Style',
  'Animal',
  'Animal',
  'Classic-Style',
  'Free Form-Style Symbol',
  'Art-Deco',
  'Art-Nouveau',
  'Religious',
  'Tassel-Style',
];

export const PENDANT_TYPE_OPTIONS = [
  'Amulet',
  'Coin',
  'Journey',
  'Stick',
  'Ballerina',
  'Cross',
  'Locket',
  'Bouquet',
  'Dog Tag',
  'Medallion',
  'Chandelier-Style',
  'Drop',
  'Circle',
  'Halo',
  'Reversible',
  'Slider',
  'Talisman',
  'Wafer',
  'Cluster',
  'Heart-Shaped',
  'Solitaire',
];
