export const RING_TYPE_OPTIONS = [
  'Solitaire',
  'Hidden Halo',
  'Company',
  'Engagement',
  'Accented',
  'Dinner',
  'Rolex-Style',
  'Rolling',
  'Solitaire Engagement',
  'Anniversary',
  'Double Gallery',
  'Semi-Mount',
  'Halo',
  'Ballerina',
  'Dress',
  'Signet',
  'Double-Halo',
  'Belcher-Style',
  'Family',
  'Sports',
  'Triple-Halo',
  'Birthstone',
  'Fashion',
  'Wedding',
  'Bouquet',
  'Cluster',
  'Bypass',
  'Eternity',
  'Championship',
  'Masonic',
  'Half-Eternity',
  'Charm',
  'Matching',
  'Semi-Eternity',
  'Claddagh',
  'Nugget',
  'Class',
  'Nugget-Style',
  'Cocktail',
  'Pinky',
  'Graduation',
  'Hidden Halo',
  'Stackable',
  'Three-Stone',
  'Three-Quarter Eternity',
  'Thumb',
  'Toe',
  'Trinity',
  'Two-Stage Gallery',
  'Urn',
  'Coin',
  'Puzzle',
  'Watch',
];

export const RING_SHANK_OPTIONS = [
  'With A Braided/twisted Shank',
  'With A Bypass Shank',
  'With A Cathedral Shank',
  'With A Comfort-Fit Shank',
  'With A Continental Shank',
  'With A Euro-Shank',
  'With A Flat Shank',
  'With A Half Round Shank',
  'With A Hinged/clip-On Shank',
  'With A Knife-Edge Shank',
  'With A Ring Guard',
  'With A Slightly Rounded Shank',
  'With A Soft-Square Shank',
  'With A Split Euro-Shank',
  'With A Split-Shank',
  'With A Stirrup Shank',
  'With A Tapered Shank',
  'With A Tapered, Comfort-Fit Shank',
  'With A U-Shape Sizing Bar(s)',
  'With An Adjustable Shank',
  'With Sizing Balls',
  'With Sizing Bars',
  'With Stabilizers',
];

export const RING_SIZES_OPTIONS = [
  '3',
  '3.5',
  '4',
  '4.5',
  '5',
  '5.5',
  '6',
  '6.5',
  '7',
  '7.5',
  '8',
  '8.5',
  '9',
  '9.5',
  '10',
  '10.5',
  '11',
  '11.5',
  '12',
  '12.5',
  '13',
  '13.5',
];
