export const BRAND_OPTIONS = [
  'A. Lange & Sohne',
  'Corum',
  'Iwc',
  'Richard Mille',
  'Apple',
  'Cyma',
  'Iwc Shaffhausen',
  'Rolex',
  'Audemars Piguet',
  'Eterna',
  'Baume',
  'Ferrari',
  'Jaeger-Lecoultre',
  'Longines',
  'Rotary',
  'Seiko',
  'Baume & Mercier',
  'Fortis',
  'Mont Blanc',
  'Tag Heuer',
  'Bell & Ross',
  'Franck Muller',
  'Movado',
  'Tissot',
  'Blancpain',
  'Frederique Constant',
  'Nomos',
  'Tudor',
  'Breguet',
  'Girard-Perregaux',
  'Officine Panerai',
  'Breitling',
  'Glashütte Original',
  'Omega',
  'Bvlgari',
  'Grand Seiko',
  'Oris',
  'Carl F. Bucherer',
  'Gucci',
  'Panerai',
  'Cartier',
  'Hamilton',
  'Certina',
  'Chopard',
  'Hermes',
  'Harry Winston',
  'Parmigiani',
  'Patek Philippe',
  'Piaget',
  'Ulysse Nardin',
  'Vacheron Constantin',
  'Van Cleef & Arpels',
  'Victorinox',
  'Zenith',
  'Concord',
  'Hublot',
  'Rado',
];

export const WATCH_TYPE_OPTIONS = ['Wristwatch', 'Watch', 'Pocket Watch'];

export const WATCH_COUNTRY_OPTIONS = [
  'American Made',
  'French Made',
  'British Made',
  'German Made',
  'Japanese Made',
  'Swiss Made',
  'Russian Made',
];

export const WATCH_BOX_OPTIONS = [
  'With Original Box And Papers',
  'With Original Box',
  'With Original Papers',
];
