export const FIRST_BUSSINESS_IN_LOCATION_HEADER_NAME = 'BUSINESS LOCATION ID';

export const IMAGE_COLUMN_NAME = 'IMAGE';

export const PRODUCTS_EXPECTED_VALUES = [
  'BARCODE ID',
  'NAME',
  'DEFAULT PRICE',
  'PRODUCT TYPE',
  'BRAND',
  'MODEL',
  'DIMENSION LENGTH',
  'DIMENSION WIDTH',
  'DIMENSION HEIGHT',
  'DIMENSION UNIT',
  'WEIGHT',
  'WEIGHT UNIT',
  'SKU',
  'UPC',
  'MPN',
  'EAN',
  'ISBN',
  'PARTS WARRANTY',
  'LABOR WARRANTY',
  'DESCRIPTION',
  'ECOMMERCE DESCRIPTION',
  'SHOPIFY TAGS',
  'ALLOW NEGATIVE QUANTITY',
  'VISIBLE ITEM',
];
export const DEFAULT_PRICE_INDEX =
  PRODUCTS_EXPECTED_VALUES.indexOf('DEFAULT PRICE');

export const PRODUCT_ITEMS_HEADER_NAME = 'PRODUCTS IN LOCATIONS';

export const PRODUCT_ITEM_VALUES = [
  FIRST_BUSSINESS_IN_LOCATION_HEADER_NAME,
  'QUANTITY',
  'PRODUCT COST',
  'VENDOR',
  'ORDER CREATION DATE',
  'PAYMENT AMOUNT',
  'MEMO',
  'MEMO DUE DATE',
  'SERIALIZED',
];

export const APP_ID = 'APP ID';

export const ADDITIONAL_REPEATABLE_ITEM_VALUES = 'SERIAL NUMBER';

export const CUSTOM_FIELDS_HEADER = 'CUSTOM FIELDS';
