export const FIRST_ORDER_ITEM_COLUMN = 'PRODUCT ID';

export const ORDERS_EXPECTED_VALUES = [
  'CUSTOMER',
  'EMPLOYEE',
  'STATUS',
  'CREATED DATE',
  'BUSINESS LOCATION',
  'PAID OFF',
  'DUE DATE',
  'LAYAWAY',
];

export const ORDER_PRODUCT_VALUES = [
  FIRST_ORDER_ITEM_COLUMN,
  'QUANTITY',
  'PRICE',
  'TAX NAME',
  'NOTE',
];

export const ADDITIONAL_REPEATABLE_ITEM_VALUES = 'SERIAL NUMBER';
export const IMAGE_COLUMN_NAME = 'IMAGE';
