export const STONE_CUT_STYLE_OPTIONS = [
  'Brilliant Cut',
  'Modified Brilliant Cut',
  'Cabochon Cut',
  'Checkerboard Cut',
  'Faceted, Cabochon Cut',
  'Checkerboard, Cabochon Cut',
  'Briolette Cut',
  'Double Cabochon Cut',
  'Bead',
  'Cameo',
  'Carved',
  'Disc Cut',
  'Faceted Fancy Cut',
  'Fantasy Cut',
  'Flat',
  'French Cut',
  'Intaglio',
  'Laser Cut',
  'Mixed Cut',
  'Scissors Cut',
  'Step Cut',
  'Rose Cut',
  'Tablet Cut',
  'Tumbled',
];
