export const GEMSTONE_SHAPE_OPTIONS = [
  'Round-Shaped Baguette',
  'Briolette',
  'Cut-Corner Triangular-Shaped',
  'Emerald-Cut',
  'Emerald-Shaped',
  'Fancy-Shaped',
  'Freeform Half-Moon',
  'Heart-Shaped',
  'Hexagonal-Shaped',
  'Marquise-Shaped',
  'Octagonal-Shaped',
  'Oval-Shaped',
  'Pear-Shaped',
  'Pentagonal-Shaped',
  'Princess Cut',
  'Rectangular Cushion-Shaped',
  'Rectangular-Shaped',
  'Rough',
  'Square Cushion-Shaped',
  'Square Emerald',
  'Square-Shaped',
  'Tapered Baguette',
  'Trapezoid-Shaped',
  'Triangular-Shaped',
  'Whistle-shaped',
  'Trilliant',
  'Shield',
  'Cut-Corner Rectangular-Shaped',
  'Cut-Corner Square-Shaped',
  'Kite-Shaped',
  'Lozenge-Shaped',
  'Square Step',
];

export const DIAMOND_SHAPE_OPTIONS = [
  'Round Brilliant',
  'Single',
  'Early Round Brilliant',
  'Oval Brilliant',
  'Pear-Shape Brilliant',
  'Marquise Brilliant',
  'Heart-Shape Brilliant',
  "Calf's Head",
  'Epaulette',
  'Old European',
  'Old Mine',
  'Dutch Rose',
  'Triangle',
  'Trilliant',
  'Lozenge',
  'Baguette',
  'Shield',
  'Tapered Baguette',
  'Old Swiss',
  'Rose',
  'Crown of LightTM',
  'Keystone',
  'Trapezoid Brilliant',
  'Trapezoid Step',
  'Briolette',
  'Pentagonal-Shaped',
  'Crescent',
  'Floetings',
  'Half Moon Brilliant',
  'Bead',
  'Horse Head',
  'Bullet-Shaped',
  'Kite-Shaped',
  'Cushion Brilliant',
  'Square Step',
  'Cut-Cornered Rectangular Modified',
  'Cut-Cornered Square Modified Brilliant',
  'Radiant',
  'French',
  'Princess',
  'Brilliant',
  'Square Modified Brilliant',
  'Tycoon',
  'Emerald',
  'Hexagonal Brilliant Hexagonal Step Cut',
  'Octagonal Brilliant',
  'Rectangular Step',
  'Table',
  'Flanders',
  'Asscher',
  'Lucère',
  'Square Emerald',
  'Dream',
  'Ideal',
  'Peruzzi',
];
