export const STONE_TYPE_OPTIONS = [
  'Agate',
  'Almandine Garnet',
  'Almandine-Spessartine',
  'Alexandrite',
  'Amber',
  'Amazonite',
  'Amethyst',
  'Ammonite',
  'Ammolite',
  'Ammolite Doublet',
  'Ammolite Triplet',
  'Andalusite',
  'Andradite Garnet',
  'Angel Skin Coral',
  'Ametrine',
  'Apatite',
  'Aquamarine',
  'Beryl',
  'Benitoite',
  'Bi-Color Sapphire',
  'Bi-Color Tourmaline',
  'Black Coral',
  'Black Opal',
  'Black Spinel',
  'Black Star Sapphire',
  'Bloodstone',
  'Blue Star Sapphire',
  'Blue Topaz',
  'Blue Zircon',
  'Blue, Cabochon',
  'Brazilian Emerald',
  'Brown Zircon',
  'Burmese Sapphire',
  'Cabochon Emerald',
  'Cabochon Ruby',
  'Carnelian',
  "Cat's Eye Chrysoberyl",
  "Cat's Eye Tourmaline",
  'Ceramic Bead',
  'Chalcedony',
  'Chrome Diopside',
  'Chrome Pyrope Garnet',
  'Chrome Tourmaline',
  'Chrysoberyl',
  'Chrysocolla',
  'Chrysoprase',
  'Citrine',
  'Colombian Emerald',
  'Color-Change Garnet',
  'Color-Change Sapphire',
  'Colorless Sapphire',
  'Colorless Spinel',
  'Coral',
  'Corundum',
  'Cuprian Tourmaline',
  'Cubic Zirconia',
  'Danburite',
  'Demantoid Garnet',
  'Diaspore',
  'Dravite Tourmaline',
  'Dyed Howlite',
  'Emerald',
  'Fire Opal',
  'Fluorite',
  'Foil Back',
  'G.G.G. (Gadolinium Gallium Garnet)',
  'Garnet',
  'Garnet and Glass Doublet',
  'Glass',
  'Glass Composite Ruby',
  'Golden Beryl/Heliodor',
  'Golden Coral',
  'Gold Quartz',
  'Goshenite',
  'Green Beryl',
  'Green Chrysoberyl',
  'Green Quartz',
  'Green Sapphire',
  'Green Tourmaline',
  'Greened Amethyst',
  'Grossular Garnet',
  'Grossular Garnet (Mint)',
  'Heated Sapphire',
  'Heliotrope',
  'Hematite',
  'Hessonite Garnet',
  'Hiddenite',
  'Howlite',
  'Hyacinth Zircon',
  'Imitation Amber',
  'Imitation Lapis Lazuli',
  'Imitation Pearl',
  'Imitation Turquoise',
  'Imperial Topaz',
  'Inoborates',
  'Indicolite Tourmaline',
  'Jade',
  'Jadeite',
  'Jasper',
  'Kunzite',
  'Kyanite',
  'Labradorite',
  'Lavender Moon Quartz',
  'Lavender Spinel',
  'Lapis Lazuli',
  'Larimar',
  'London Blue Topaz',
  'Madeira Citrine',
  'Mabe Pearl',
  'Mahenge Garnet',
  'Malaia Garnet',
  'Malachite',
  'Marcasite',
  'Matura Diamond Zircon',
  'Mint Garnet',
  'Moldavite',
  'Moonstone',
  'Morganite',
  'Mozambique Garnet',
  'Mozambique Ruby',
  'Mystic Topaz',
  'Nephrite',
  'Obsidian',
  'Onyx',
  'Opal',
  'Opal Doublet',
  'Opal Triplet',
  'Orange Sapphire',
  'Orange Spinel',
  'Orange Sunstone',
  'Oxblood Coral',
  'Padparadscha Sapphire',
  'Paraiba Tourmaline',
  'Parti Sapphire',
  'Pearl',
  'Peridot',
  'Peristerite',
  'Pink Sapphire',
  'Pink Spinel',
  'Pink Topaz',
  'Pink Tourmaline',
  'Plastic',
  'Prasiolite',
  'Prehnite',
  'Pyrope Garnet',
  'Pyrope-Almandine Garnet',
  'Pyrope-Spessartite Garnet',
  'Quartz',
  'Quench Crackled Quartz',
  'Rainbow Moonstone',
  'Red Beryl',
  'Red Spinel',
  'Rhodochrosite',
  'Rhodolite Garnet',
  'Rhodonite',
  'Rhinestone',
  'Rock Crystal Quartz',
  'Rose Quartz',
  'Ruby',
  'Rubellite Tourmaline',
  'Rubicelle Spinel',
  'Rutilated Topaz',
  'Salmon Coral',
  'Sapphire',
  'Scapolite',
  'Silver Quartz',
  'Sky Blue Topaz',
  'Slocum Stone',
  'Smoky Quartz',
  'Sodalite',
  'Spessartine Garnet',
  'Spessartine-Mandarin Garnet',
  'Spessartite Garnet',
  'Spinel',
  'Spodumene',
  'Star Ruby',
  'Star Sapphire',
  'Swiss Blue Topaz',
  'Synthetic Alexandrite',
  'Synthetic Amethyst',
  'Synthetic Citrine',
  'Synthetic Color-Change Sapphire',
  'Synthetic Diamond',
  'Synthetic Emerald',
  'Synthetic Fluorite',
  'Synthetic Moissanite',
  'Synthetic Opal',
  'Synthetic Rose Quartz',
  'Synthetic Ruby',
  'Synthetic Sapphire',
  'Synthetic Smoky Quartz',
  'Synthetic Spinel',
  'Synthetic Spinel Triplet',
  'Synthetic Star Ruby',
  'Synthetic Star Sapphire',
  'Synthetic Turquoise',
  'Synthetic Zircon',
  'Tanzanite',
  'Thulite',
  "Tiger's Eye Quartz",
  'Topaz',
  'Topazolite Garnet',
  'Tourmaline',
  'Trapiche Emerald',
  'Tri-Color Tourmaline',
  'Turkish Diaspore',
  'Turquoise',
  'Uvarovite Garnet',
  'Unenhanced Blue Burmese Sapphire',
  'Unenhanced Pink Sapphire',
  'Unenhanced Purple Sapphire',
  'Unenhanced White Sapphire',
  'Unenhanced Yellow Sapphire',
  'Varascite',
  'Water Opal',
  'Watermelon Tourmaline',
  'White Opal',
  'White Topaz',
  'Yellow Chrysoberyl',
  'Yellow Sapphire',
  'Yellow Topaz',
  'Y.A.G. (Yttrium Aluminium Garnet)',
  'Zambian Emerald',
  'Zircon',
  'Zoisite',
  'Zultanite',
];
