import { ImportRule } from '@components/dashboard/dashboardSettings/SettingsModuleFactory/sections/importEntity/types/types';
import { EnumSizeUnit, EnumWeightUnit } from '@helpers/enumTypes';

export const PRODUCTS_IMPORT_RULES: ImportRule[] = [
  {
    title: 'Proper headers',
    description: `The headers in your file must match the example file exactly. Ensure proper capitalization, spelling, and column order. You may add as many IMAGE and SERIAL NUMBER columns as you like, but make sure they are placed correctly`,
  },
  {
    title: 'Existing Business Locations',
    description:
      'Ensure that business locations already exist before importing. Copy the location IDs from the upper menu to associate the product with a valid location.',
  },
  {
    title: 'Barcode',
    description: 'The barcode and product name must be unique.',
  },
  {
    title: 'Valid Numbers',
    description:
      'The default price, dimension properties, weight, quantity, product cost, and payment amount must be valid numbers. Ensure they are correctly formatted and do not contain invalid characters.',
  },
  {
    title: 'All if One',
    description:
      'If any dimension properties (e.g., length, width, height, unit), weight properties, or product-in-location properties are provided, all related properties must also be provided.',
  },
  {
    title: 'Weight Unit',
    description: `The weight unit must be one of the following: ${Object.values(
      EnumWeightUnit,
    ).join(
      ', ',
    )}. This guarantees that the weight conforms to a standard unit of measurement.`,
  },
  {
    title: 'Dimension Unit',
    description: `The dimension unit must be one of the following: ${Object.values(
      EnumSizeUnit,
    ).join(
      ', ',
    )}. This ensures consistency in the measurement of product dimensions.`,
  },
  {
    title: 'Valid Dates',
    description:
      'The parts warranty, labor warranty, and order creation date must be valid dates. Ensure that the dates follow a consistent format, such as YYYY-MM-DD.',
  },
  {
    title: 'Images',
    description:
      'Images must be uploaded via the "Upload Images" button. After uploading, copy the IDs from the generated file and associate them with the product.',
  },
  {
    title: 'Quantity',
    description:
      'The quantity of the product in a location must exceed the current quantity for correct updating.',
  },
  {
    title: 'Valid Emails',
    description:
      'The email of vendor must be a valid email address associated with a contact or company.',
  },
];

export const BULK_CHANGE_DEFAULT_PRICE_RULES: ImportRule[] = [
  {
    title: 'Required headers',
    description:
      'Your file must include two columns: Product ID and Default Price.',
  },
  {
    title: 'Product ID',
    description:
      'A unique identifier generated by CaratIQ for each product. You can find it by exporting the Inventory Report.',
  },
  {
    title: 'Default Price',
    description:
      'Enter the new default price you want to set for the item. Use a positive number only, with no currency symbol.',
  },
];
