export const customPermissions = {
  owner: {
    dashboard: true,
    crm: true,
    hr: true,
    tasks: true,
    employeeScheduling: true,
    reports: true,
    selling: true,
    inventory: true,
    allowAddOrRemoveOptionsInProductSelect: true,
    productItemCostVisible: true,
    productItemRelationVisible: true,
    rentals: true,
    accounting: true,
    contracts: true,
    marketing: true,
    websiteEditor: true,
    location: true,
    integrations: true,
    settings: true,
    price: true,
  },
  employee: {
    dashboard: true,
    crm: false,
    hr: false,
    tasks: false,
    employeeScheduling: false,
    reports: false,
    selling: true,
    inventory: true,
    allowAddOrRemoveOptionsInProductSelect: true,
    productItemCostVisible: true,
    productItemRelationVisible: true,
    rentals: true,
    accounting: true,
    contracts: true,
    marketing: true,
    websiteEditor: true,
    location: true,
    integrations: true,
    settings: true,
    price: false,
  },
};
