export const documentsDefaultsTooltipText =
  'Enabling this switch will include this text in autogenerated files';

export const settingsTitleStyles = {
  fontSize: 14,
  fontWeight: 500,
  color: '#1F2933',
  margin: 0,
};

export const settingsDescriptionStyles = {
  fontSize: 12,
  color: '#747679',
};
